### ISSUE TITLE
[FEAT]: Data Service `Simulation Results` CRUD API

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/data-service#18]
**Describe the solution you'd like**
  - [x] Implement all CRUD endpoints to manage a user `Simulation Results`
  - [x] Mock at least one _simulation results_ containing from a mock _simulation plan_
  - [x] Write test for all endpoints

**Comment by fivegrant** [comment]
`/results` will wrap a subset of datasets

**Comment by fivegrant** [comment]
see v0.3.0
