### ISSUE TITLE
[FEAT]: Data Service `Simulation Plan` CRUD API

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/data-service#19]
**Describe the solution you'd like**
  - [x] Implement all CRUD endpoints to manage a user `Simulation Plan`
  - [x] Mock at least one _simulation plan_ containing mock model(s), dataset(s), parameters, etc.
  - [x] Write test for all endpoints

**Comment by fivegrant** [comment]
see v0.3.0
