### ISSUE TITLE
[FEAT]: Data Service `Model Metadata` CRUD API

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/data-service#22]
**Describe the solution you'd like**
  - [x] Implement all CRUD endpoints to manage a `Model Metadata`
  - [x] Mock at least one _model_ containing mock _metadata_
  - [x] Write test for all endpoints

**Comment by fivegrant** [comment]
The endpoints are currently mocked up, but unit tests need to be implemented for them. (a few light fixes likely needed)

**Comment by fivegrant** [comment]
see v0.3.0
