### ISSUE TITLE
Converge on workflow model data structure

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/data-service#228]
It looks like there are some scrubbing code in TDS, some of the fields disappeared after I POSTED a workflow through the API. Can we, for the time being, converge on this format below?

```
interface Workflow {
	id: string;
	name: string;
	description: string;

	// zoom x-y translate and zoom
	transform: {
		x: number;
		y: number;
		k: number;
	};
	nodes: WorkflowNode[];
	edges: WorkflowEdge[];
}
```

Where transform is an object/dict, and nodes/edges are lists of dicts

**Comment by toddroper** [comment]
@mwdchang What are the data structures for the `WorkflowNode` and `WorkflowEdge` types?  Or do we just want to have a basic list of dicts for that?

**Comment by toddroper** [comment]
@mwdchang I tested the workflow with this data and it looks like everything is working as expected.

**Comment by toddroper** [comment]
Updated workflow has been moved to staging.
