### ISSUE TITLE
Unable to get Models (Branch 0.4.0)

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/data-service#232]
Likely related to issue 230 
<img width="613" alt="image" src="https://github.com/DARPA-ASKEM/data-service/assets/17088680/6daa6400-8021-4e6a-ae7e-64dfab700152">

Let me know if you need more information than the screenshot provides!

**Comment by toddroper** [comment]
@Tom-Szendrey Do you have models created in the system?  It appears to be responding with a `200` but empty list in the body.

**Comment by toddroper** [comment]
No problem, glad it was a minor blip.
