### ISSUE TITLE
[FEAT]: Data Service `Projects` CRUD API

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/data-service#24]
**Describe the solution you'd like**
  - [x] Implement all CRUD endpoints to manage a user `Project`
  - [x] Mock at least one project containing mock model(s), dataset(s), metadata
  - [x] Write test for all endpoints

**Comment by fivegrant** [comment]
@mattprintz's comments about users from #25 will also be included wtth the addition of the `Projects` CRUD endpoints

**Comment by fivegrant** [comment]
see v0.3.0
