### ISSUE TITLE
Thin thread API call walk through

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/data-service#30]
1. `CREATE` framework called `Petri Net` (script load common frameworks)
2. `CREATE` person `JohnSmith@gmail.com`
3. `CREATE` project called `MyProject`; specify this was created by `John Smith` [keep track of this project id!]
4. `CREATE` publication with xDD id `616cf16267467f7269ccde6f`. The ID is in `document_xdd-gddid.txt`
5. `UPDATE` project with asset for `MyProject` indicating that the publication is an asset of the project
6. `CREATE` intermediate `intermediate_xyz` from MIRA that’s a MIRA meta template where the representation is from `model_mmt-templates.json`
7. `UPDATE` project with asset for `MyProject` indicating that the intermediate is an asset of the project
8. `CREATE` provenance relation: `intermediate_xyz` is derived from `616cf16267467f7269ccde6f`
9. `CREATE` model called `petri_xyz` from model_petri.json and has the “Petri Net” framework
10. `UPDATE` project with asset for `MyProject` attaching `petri_xyz` to it
11. `CREATE` provenance relation: `petri_xyz` is derived from `intermediate_xyz`
12. `CREATE` simulation plan `MySim` from simulation-plan_ATE.json with associated model `petri_xyz`
13. `CREATE` provenance relation: `MySim` relies on `petri_xyz`
14. `UPDATE` project with asset for `MyProject` attaching `MySim` to it
15. `CREATE` parameters from `model_mmt-parameters.json` associated with simulation `MySim`. This should create 28 parameters records in the database
16. `CREATE` simulation run `MyRun` from file (TBD) associated with `MySim`
17. `CREATE` dataset `MyData` from simulation run `MyRun`
18. `CREATE` provenance relation: `MyData` is derived from `MyRun`

**Comment by fivegrant** [comment]
all of the necessary endpoints should be in `main`. will reopen if something is lacking witht the thinthread
