### ISSUE TITLE
Hard limit of 10 items per project asset type

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/data-service#304]
Currently the `GET /projects/{project_id}/assets` endpoint returns a maximum of 10 assets per type. This is because we don't specify a `size` parameter when we [query ES for project assets](https://github.com/DARPA-ASKEM/data-service/blob/main/tds/modules/project/controller.py#L314-L318). This enforces a hard limit on only 10 assets being returned even with an `ids` query.

We have a few options:

1. Specify the `size` based on the number of `ids` to be fetched. Get's arbitrarily large and can't exceed 10,000 assets of each type.
2. Allow the HMI to specify the `size` when it calls `GET /projects/{project_id}/assets`. This gives more control to the HMI over the response `size`.
4. Implement pagination on the `GET` for project assets.

@YohannParis @mwdchang please weigh in on your preference around how you'd like the HMI to be pulling these assets.

**Comment by brandomr** [comment]
Updated the options a bit. Even though this is an `ids` query, it will still only return `10` items by default, even if the length of the `ids` array it's passed > 10.

**Comment by YohannParis** [comment]
Do we need to have a limit to return this call, will it be unlikely for a user to have abnormally huge asset lists?
Should we just set it to 1000 each and move on for now, I feel lick this is a transition issue.
