### ISSUE TITLE
Add `assets` to `documents`

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/data-service#326]
We need to be able to add `assets` to a `document`. These will be individual files that will be either figures, images, and equations. We should examine an example payload from Cosmos to determine the most appropriate way to store these. It may be something like:

```
"assets": {
   "equations": [{"metadata": {}, "file_name": "foo.txt"}],
   "images": [{"metadata": {}, "file_name": "zap.img"}],
   "figures": [{"metadata": {}, "file_name": "zonk.fig"}],
}
```

@YohannParis I know we discussed having these assets be an arbitrary list, but I think it will benefit the HMI to know what they are more explicitly. Thoughts?

**Comment by YohannParis** [comment]
This sounds good to me, but I wonder if it will be simpler to be a value in the `metadata` object instead of a main property. In case we get more in the future?

```JSON
"assets": [
    {
        "file_name": "foo.txt", 
        "metadata": { "type": "equations" }
    },
    {
        "file_name": "zap.img", 
        "metadata": { "type": "images" }
    },
    {
        "file_name": "zonk.fig", 
        "metadata": { "type": "figures" }
    }
]
```

**Comment by brandomr** [comment]
Good call. FYI @Sorrento110

**Comment by brandomr** [comment]
@Sorrento110 we need `tables` as well since they handle them separately
