### ISSUE TITLE
Convert `Code` `dynamics.block` into an array

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/data-service#332]
Currently a `Code.file.dyanmics.block` [is a string](https://github.com/DARPA-ASKEM/data-service/blob/main/tds/modules/code/model.py#L18). I think this was a mistake; since there can only be one `dynamics` per `file` we should convert this to an array in case the `dynamics` are described in multiple locations within the same file.

@YohannParis @Sorrento110 @tangopapatime @mwdchang thoughts?

**Comment by YohannParis** [comment]
I am curious if different dynamics can exists on the same file.
Or maybe the user wants to highlight different part of the code not just for retrieving dynamics, but a different configuration for example.

**Comment by brandomr** [comment]
Addressed by #334
