### ISSUE TITLE
Implement vector search in ES

### ISSUE THREAD

**Issue by brandomr** [DARPA-ASKEM/data-service#337]
Currently we provide only basic search over models, documents, datasets, etc that are stored in TDS Elasticsearch. This issue addresses that by proposing implementing vector storage within ES for targeted fields/objects and can be implemented similarly to how this was handled by Dojo.

**Comment by mattprintz** [comment]
I have confirmed that the version of ES used in Terarium does indeed allow vector embeddings. We just need to figure out the dimensions and any other information we want to store/index.
