### ISSUE TITLE
Save `xDD` extractions when importing Publications as `Documents`

### ISSUE THREAD

**Issue by YohannParis** [DARPA-ASKEM/data-service#350]
When a user select a Publication on the _Data Explorer_ they can visualize all the _xDD_ extractions.
But once the user import the selected Publication in their `Project`, none of those informations are saved into the newly created `Document`. i.e. _GitHub_ repository links, that are only available into _xDD_ and not in _COSMOS_.
Also, after running _COSMOS_, we should keep the extractions as well.

**Comment by brandomr** [comment]
@YohannParis I wonder if what we actually want is some endpoint in KM that is like `/xdd_to_document` which would take in an xDD `id` and copy over all the relevant metadata to create a new document in TDS. It could then send the PDF of the publication to Cosmos for further extractions (if this is needed/relevant)?

An alternative would be for HMI server to format and send all the xDD information it has on hand (that the user is viewing) to TDS when it makes the `document`--we'd need to ensure the `document` model can support all the things xDD has.

Another option would be to have the `/xdd_to_document` endpoint live in TDS. 

No preference on my end--but these are only for xDD publications for which we can pull the PDF from unpaywall right?

**Comment by YohannParis** [comment]
@brandomr I see your point.

I'll vote for number two where the `hmi-server` takes care to create a `Document` itself on `data-service` and then we can add all the extractions provided from _xDD_.

Therefore, could you create a way for us to send extractions fils to `data-service` PUT `Document` endpoint? That will push the files to S3, or at least create S3 links for uploading?

@dvince2 what do you think of this?

**Comment by dvince2** [comment]
I think that sounds right and feels appropriate for it to live in HMI-Server.  Once the tds documents api is updated to handle the new datatypes on documents we can pull it from xdd and package up the new document for TDS

**Comment by brandomr** [comment]
Right now you actually can save `assets` (the Cosmos/xDD extractions) on the `document` when you create the document. 

Here is [the model](https://github.com/DARPA-ASKEM/data-service/blob/main/tds/modules/document/model.py#L12-L25) for those. Something like:

```
    {
      "file_name": "figure1.png",
      "asset_type": "image",
      "metadata": {
        "type": "figures",
        "description": "Figure showing the spread rate",
        "dimensions": "1200x800"
      }
    }
```

Not that `asset_type` is just a string, not a a fixed vaocabulary so you _could_ put things besides `image`, `equation`, or `figure`. For a `github_url` I think putting that into the `document.metadata` at `github_url` might make the most sense.

For each `file_name` of the assets what you'd do is individually generate the pre-signed upload URL then `POST` them to S3. We are now also storing the entire zipfile as we discussed previously so if you're relying on that you could bypass uploading individual files and just upload only the whole zipfile.

**Comment by dvince2** [comment]
@brandomr is it worth it at this time to standardize what "asset_type" could be for safety?

**Comment by brandomr** [comment]
yep I think it would be worth doing and pretty trivial. I can do that today

**Comment by dvince2** [comment]
for `github_url`, documents from xdd can have multiple github urls. Should this be a list of urls?

**Comment by dvince2** [comment]
re: @brandomr asset_type types... this is the full list of types that xDD can return.  Do these look like the correct typings?

"Section Header" == IGNORE
"Body Text" == IGNORE
"Figure" == `Figure`
"Figure Caption" == IGNORE
"Table" == `Image`
"Equation" == `Equation`
"Page Footer" == IGNORE
"Page Header" == IGNORE
"Table Caption" == IGNORE
"Other" == IGNORE
"Reference text" == IGNORE

**Comment by brandomr** [comment]
Right now we're only storing `figure` , `image` and `equation` as assets--should we look into the others? Those are in the raw response from Cosmos but they don't have any external asset (e.g. a `.png` o the equation) associated with them.
